"""remove_bid_id_column_from_bids_table

Revision ID: 0ac5c502beaf
Revises: 9caf81255a9e
Create Date: 2025-07-13 03:54:44.943708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac5c502beaf'
down_revision: Union[str, Sequence[str], None] = '9caf81255a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bids_bid_id'), table_name='bids')
    op.drop_column('bids', 'bid_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('bid_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_bids_bid_id'), 'bids', ['bid_id'], unique=True)
    # ### end Alembic commands ###
