"""Add image_url column to products table

Revision ID: 44df0db80805
Revises: 82ae1aad63ba
Create Date: 2025-07-13 00:03:13.074922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44df0db80805'
down_revision: Union[str, Sequence[str], None] = '82ae1aad63ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bids_bid_id_key'), 'bids', type_='unique')
    op.drop_index(op.f('ix_bids_bid_id'), table_name='bids')
    op.create_index(op.f('ix_bids_bid_id'), 'bids', ['bid_id'], unique=True)
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_index(op.f('ix_bids_bid_id'), table_name='bids')
    op.create_index(op.f('ix_bids_bid_id'), 'bids', ['bid_id'], unique=False)
    op.create_unique_constraint(op.f('bids_bid_id_key'), 'bids', ['bid_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
