"""Add current_bid column to products table

Revision ID: 9caf81255a9e
Revises: 44df0db80805
Create Date: 2025-07-13 02:20:55.916732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caf81255a9e'
down_revision: Union[str, Sequence[str], None] = '44df0db80805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('current_bid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'current_bid')
    # ### end Alembic commands ###
